### ISSUE TITLE
为什么无法从池中获取资源啊，需要Redis？

### ISSUE THREAD

**Issue by Liyff** [WongSilver/attendance_management_api#1]
![image](https://github.com/WongSilver/attendance_management_api/assets/100138334/cfa0eeef-46db-4729-99d4-f4bf05013783)

**Comment by WongSilver** [comment]
需要安装redis

**Comment by Liyff** [comment]
感谢

**Comment by WongSilver** [comment]
> 感谢

非常感谢捐赠👏
